# Generated by Django 2.1.4 on 2019-03-06 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked_tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_seat_no', models.CharField(max_length=10)),
                ('ticket_book_from', models.CharField(max_length=50)),
                ('ticket_booking_website', models.CharField(max_length=100)),
                ('ticket_booking_tranc_id', models.CharField(max_length=100)),
                ('ticket_booking_username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_rating', models.CharField(max_length=50)),
                ('movie_review', models.CharField(max_length=500)),
                ('movie_trailer_link', models.CharField(max_length=100)),
                ('movie_poster_link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=50)),
                ('adressline1', models.CharField(max_length=50)),
                ('adressline2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('state', models.CharField(max_length=50)),
                ('screen_no', models.CharField(max_length=5)),
                ('seat_string', models.CharField(max_length=500)),
                ('theatre_rating', models.CharField(max_length=50)),
                ('now_playing', models.CharField(max_length=50)),
                ('up_coming', models.CharField(max_length=50)),
                ('theatre_merchant_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_booking_website_details',
            fields=[
                ('merchant_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ticket_booking_website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_price_and_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_timings', models.TimeField()),
                ('date', models.DateField()),
                ('seat_class', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.movie')),
                ('theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.theatre')),
            ],
        ),
        migrations.AddField(
            model_name='booked_tickets',
            name='movie_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theatre.ticket_price_and_time'),
        ),
    ]
