# Generated by Django 2.1.4 on 2019-03-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_auto_20190306_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_rating',
            new_name='imdbmovie_rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_review',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_movie_review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
