# Generated by Django 2.1.4 on 2019-03-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_auto_20190307_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdbmovie_rating',
            new_name='imdb_movie_rating',
        ),
    ]
