# Generated by Django 2.1.4 on 2019-03-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0005_auto_20190307_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_movie_review',
            new_name='movie_description',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_release_date',
            field=models.DateField(),
        ),
    ]
