# Generated by Django 2.1.4 on 2019-03-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0007_auto_20190307_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_poster_link',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster_1',
            field=models.ImageField(blank=True, upload_to='poster_1'),
        ),
    ]
