# Generated by Django 2.1.4 on 2019-03-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0008_auto_20190316_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket_price_and_time',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_poster_2',
            field=models.ImageField(blank=True, upload_to='poster_2'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='now_playing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='now_playing', to='theatre.movie'),
        ),
        migrations.AlterField(
            model_name='theatre',
            name='up_coming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='up_coming', to='theatre.movie'),
        ),
    ]
