# Generated by Django 2.1.4 on 2019-04-17 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_release_date', models.DateField()),
                ('movie_language', models.CharField(max_length=100)),
                ('theatre_name', models.CharField(max_length=50)),
                ('adressline1', models.CharField(max_length=50)),
                ('adressline2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('screen_no', models.CharField(max_length=5)),
                ('show_timings', models.TimeField()),
                ('show_date', models.DateField()),
                ('seat_no', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('date_and_time_of_booking', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_release_date', models.DateField()),
                ('movie_age_rating', models.CharField(max_length=100)),
                ('movie_duration_mins', models.CharField(max_length=100)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_actors', models.CharField(max_length=100)),
                ('movie_directors', models.CharField(max_length=100)),
                ('movie_producers', models.CharField(max_length=100)),
                ('movie_writers', models.CharField(max_length=100)),
                ('imdb_movie_rating', models.CharField(max_length=50)),
                ('movie_description', models.TextField()),
                ('movie_trailer_link', models.CharField(max_length=100)),
                ('movie_poster_1', models.ImageField(blank=True, upload_to='poster_1')),
                ('movie_poster_2', models.ImageField(blank=True, upload_to='poster_2')),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=50)),
                ('adressline1', models.CharField(max_length=50)),
                ('adressline2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('screen_no', models.CharField(max_length=5)),
                ('seat_string', models.TextField()),
                ('theatre_rating', models.CharField(max_length=50)),
                ('now_playing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='now_playing', to='movies_and_cinemas.movie')),
                ('up_coming', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='up_coming', to='movies_and_cinemas.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_price_and_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_timings', models.TimeField()),
                ('date', models.DateField()),
                ('seat_class', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('theatre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_and_cinemas.theatre')),
            ],
        ),
        migrations.CreateModel(
            name='updat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
